name: 'Rsync Copy'
description: 'Copies the files from your repository to a remote host using rsync'
author: 'temper'
inputs:
  # $1
  port:
    description: 'Port for SCP'
    default: 22
  # $2
  host:
    description: 'IP Address or DNS of your target host'
  # $3
  source:
    description: 'Source route folder'
    default: "./*"
  # $4
  destination:
    description: 'Destination route folder'
  # $5
  username:
    description: 'User for remote connection'
  # $7
  key:
    description: 'Private SSH key'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'send'
  color: 'black'
