name: 'Rsync Copy'
description: 'Copies the files from your repository to a remote host using rsync'
author: 'temper'
inputs:
  host:
    description: 'IP Address or DNS of your target host'
    required: true
  source:
    description: 'Source route folder'
    required: true
  destination:
    description: 'Destination route folder'
    required: true
  username:
    description: 'User for remote connection'
    required: true
  key:
    description: 'Private SSH key'
    required: true
  port:
    description: 'Port for SCP'
    default: 22
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'file-text'
  color: 'purple'
  
